set(FILE_LIST
src/imgui/imgui.cpp
src/imgui/imgui.h
src/imgui/imgui_demo.h
src/imgui/imgui_draw.cpp
src/imgui/imgui_internal.h
src/imgui/imgui_tables.cpp
src/imgui/imgui_widgets.cpp
src/imgui/imstb_rectpack.h
src/imgui/imstb_textedit.h
src/imgui/imstb_truetype.h
src/imgui/backends/imgui_impl_opengl2.cpp
src/imgui/backends/imgui_impl_opengl2.h
src/imgui/backends/imgui_impl_sdl3.cpp
src/imgui/backends/imgui_impl_sdl3.h
src/imgui_textselect/textselect.hpp
src/imgui_textselect/textselect.cpp
src/ImGuiUserConfig.h
src/C4ImGui.cpp
src/C4ImGui.h
)
